### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by Krysztophe** [gleu/pgstats#16]
For information:
I've opened an Intent To Package: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901801 and am working on it again.
My mentor is Christophe Berg.
The packaging development is done on salsa.debian.org

**Comment by gleu** [comment]
Thanks.

**Comment by Krysztophe** [comment]
BTW, the tarball on github is out of date (2015). It seems that Debian tools look at it to update the packages. Time to bump the version to 1.1?

**Comment by gleu** [comment]
Yeah, I didn't do much release because it was only a pet project. With you planning to package it, it doesn't hold anymore. Probably time to make a new release, and then work on v11 compatibility.

**Comment by gleu** [comment]
You've got a new release \o/

**Comment by Krysztophe** [comment]
Packaging updated : https://salsa.debian.org/Krysztophe-guest/pgstat

Waiting for Christoph Berg return...

**Comment by Krysztophe** [comment]
One minute ago on pgsql-pkg-debian@postgresql.org:

> The package pgstat was updated on apt.postgresql.org:
> 
> New version 1.0.1-1.pgdg+1:
> 
> pgstat         |  1.0.1-1.pgdg+1       |  sid-pgdg      |  amd64,  i386,  ppc64el,  source
> pgstat         |  1.0.1-1.pgdg100+1    |  buster-pgdg   |  amd64,  i386,  ppc64el,  source
> pgstat         |  1.0.1-1.pgdg90+1     |  stretch-pgdg  |  amd64,  i386,  ppc64el,  source
> pgstat         |  1.0.1-1.pgdg80+1     |  jessie-pgdg   |  amd64,  i386,  ppc64el,  source
> pgstat         |  1.0.1-1.pgdg18.04+1  |  bionic-pgdg   |  amd64,  i386,  ppc64el,  source
> pgstat         |  1.0.1-1.pgdg16.04+1  |  xenial-pgdg   |  amd64,  i386,  ppc64el,  source
> pgstat-dbgsym  |  1.0.1-1.pgdg+1       |  sid-pgdg      |  amd64,  i386,  ppc64el
> pgstat-dbgsym  |  1.0.1-1.pgdg100+1    |  buster-pgdg   |  amd64,  i386,  ppc64el
> pgstat-dbgsym  |  1.0.1-1.pgdg90+1     |  stretch-pgdg  |  amd64,  i386,  ppc64el
> pgstat-dbgsym  |  1.0.1-1.pgdg18.04+1  |  bionic-pgdg   |  amd64,  i386,  ppc64el
> 
> This is the first version of this package in the repository.
> 
> The public mirrors serving apt.postgresql.org are synced hourly,
> the updated packages will be available there shortly.

Happy :-)
