### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by ohrrkan** [gleu/pgstats#21]
https://github.com/gleu/pgstats/blob/3c55044f3a17d7778aeb26441b935ef217118153/pgstat.c#L740

errx  => exit the program so PQfinish can't be call. maybe : 

`	{
		 fprintf(stderr, "could not connect to database %s: %s", opts->dbname, PQerrorMessage(my_conn));
		PQfinish(my_conn);
               exit(EXIT_FAILURE);
	}`

**Comment by gleu** [comment]
Thanks for your report.
