### ISSUE TITLE
wrong version?

### ISSUE THREAD

**Issue by MichaelDBA** [gleu/pgstats#23]
I installed the pstat package for PostgreSQL v10, but when I run it, it errors out.  It looks like its looking for an old version of pg_stat_activity where the querry column used to be named, current_query.  For pg10+ it is simply query.

```
pgstat -n localhost -u repmgr -d pgbench --port=5440 -p mypass -s table
Traceback (most recent call last):
  File "/bin/pgstat", line 61, in <module>
    curs.execute(sql)
psycopg2.ProgrammingError: column "current_query" does not exist
LINE 4: ...lect count(*) as sess from pg_stat_activity where current_qu...

```

**Comment by gleu** [comment]
I guess you're mistaken here. Obviously, your pgstat program is a python script (because of the psycopg2 error) and mine is a C executable. Unless I'm wrong, you're not complaining on the right project.

**Comment by MichaelDBA** [comment]
Ha, ur right, the one i have is a python program written by Kenny Gorman way back around 2010.
