### ISSUE TITLE
Non default values

### ISSUE THREAD

**Issue by yhuelf** [gleu/pgstats#29]
https://github.com/gleu/pgstats/blob/d03a04803ae29fb885dbcf32bc07c7d252829081/pgreport_queries.h#L5

Do we want that instead?

`SELECT source, name, setting, unit FROM pg_settings
  WHERE source NOT IN ('configuration file', 'default') OR (boot_val != reset_val)
  ORDER BY source, name;`

**Comment by gleu** [comment]
I think both are right. Do you have an example where adding the OR clause changes the results?

**Comment by yhuelf** [comment]
For example, if you set `shared_buffers` to a non default value in the postgresql.conf file.

**Comment by gleu** [comment]
I just checked and I think you're right. Do you care to do a PR? otherwise, I'll fix it tomorrow. I have to go back to my hotel now. Need some sleep :-)

**Comment by yhuelf** [comment]
Done. Good night :)

**Comment by gleu** [comment]
Thank you, the PR is merged.
