### ISSUE TITLE
Compute and show hit_ratio in `pgstat -s database` 

### ISSUE THREAD

**Issue by Krysztophe** [gleu/pgstats#31]
`pgstat -s database`  shows `read` and `hit`. Computing  the hit_ratio as a percentage would be nice.

(The output of this command is already too large, but splitting it is another problem.)

**Comment by gleu** [comment]
Done with this commit.

I agree that the output is way too large. If you have any idea on how to fix this, I'm all ears.

**Comment by Krysztophe** [comment]
Tested & approved, nice !  I'll open other issues

**Comment by gleu** [comment]
Sure, go ahead.
