### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by eradman** [gleu/pgstats#6]
The License file lists _Guillaume Lelarge_ as the copyright holder, but describes the liabilities as they relate to  _Andrew Dunstan_. Can a paragraph be added to describe this condition?

**Comment by gleu** [comment]
My bad. I copied the license from a project by Andrew Dunstan, but forgot to replace his name. I'll fix this tonight. Sorry for the mistake, and thanks for the report.

**Comment by gleu** [comment]
Fixed.
