### ISSUE TITLE
-H flag seems to only affect "xlog" stats

### ISSUE THREAD

**Issue by kmoppel** [gleu/pgstats#9]
Would be also useful for table and function stats. Or better for any numeric still:)

**Comment by gleu** [comment]
I'm very sorry for my terribly late answer.

-H is mostly for units figures. I don't see which columns could have a unit on table stats. Perhaps function stats, but even there I'm not sure.

**Comment by kmoppel** [comment]
Hey. Thanks for the reply, better late than never:) Oh I see now, it just adds units like "kB" currently. But yes, I had  "humanizing" also normal numerics in mind. For example with "-s table -H" one could get currently some very large numbers shown, making it difficult to grasp the situation...so better would be to transform "109415" into "109k" and "12054254" to "1.2m" and so forth.

./pgstat -h x1.release.db -d release_x1_db -s table -H
-- sequential -- ------ index ------ ----------------- tuples -------------------------- -------------- maintenance --------------
   scan  tuples     scan  tuples         ins    upd    del hotupd   live   dead analyze   vacuum autovacuum analyze autoanalyze
 681659676  1637886123042   80250242316  208652179092      49824558 43326972 37179565 13548974 23054531 210270 12518099       4     1762955       2      131575
     28   64093     4531    6188          11      2      1      0     10      3     14       0          0       0           0
......
   1046  12054254   101375  109415           0      0      0      0      0      0      0       0          0       0           0
